### ISSUE TITLE
Integration into SystemJS core?

### ISSUE THREAD

**Issue by guybedford** [yurydelendik/system-wasm#1]
Hi Yury, I just happened to come across this from the WebAssembly issue. It could be really nice to integrate this into SystemJS core itself - I've just been working on a new dev branch for a major release that could go well with this work.

I'd be interested to hear what you think about this!

**Comment by yurydelendik** [comment]
@guybedford Nice timing. I was planning to open the similar issue at SystemJS side for better integration with it.

See also:
- https://github.com/WebAssembly/design/pull/858
- https://github.com/yurydelendik/wasmparser/
- https://gist.github.com/yurydelendik/37566c46197f6208dc457c680810f595
- http://webassembly.org/docs/modules/#integration-with-es6-modules

**Comment by guybedford** [comment]
Excellent. Would you be interested on bringing some of this into SystemJS then? Shall I open an issue to track further for that? I've been thinking a bit about handling automatic detection as well between wasm and es modules and that would be a nice aspect to tackle too.

**Comment by yurydelendik** [comment]
> Shall I open an issue to track further for that?

Yes, please. Or I'll do that later -- I wrote the code long ago and need to refresh my memory why I hacked so much.

**Comment by guybedford** [comment]
Ok will do that now. It might also still be nice to have a `wast` plugin as a separate project potentially if there are ways to do that as well.

**Comment by guybedford** [comment]
Created https://github.com/systemjs/systemjs/issues/1482.
